# Generated by Django 2.2.19 on 2021-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210421_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default='missing news description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(default='missing news details...'),
        ),
    ]
