# Generated by Django 2.2.19 on 2021-04-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.TextField(default='#'),
        ),
    ]
